set search_path to MoPlatform;

CREATE TABLE Store (
  StoreID BIGSERIAL PRIMARY KEY,
  Code VARCHAR(20),
  Name VARCHAR(255) NOT NULL,
  Address VARCHAR(255),
  Tel VARCHAR(20),
  Email VARCHAR(50),
  Owner VARCHAR(50),
  Status INTEGER,
  UNIQUE (Code)
);

CREATE TABLE Product (
  ProductID BIGSERIAL PRIMARY KEY,
  Code VARCHAR(50) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  UNIQUE (Code)
);

CREATE TABLE Invoice (
  InvoiceID BIGSERIAL PRIMARY KEY,
  InvoiceNo VARCHAR(50) NOT NULL,
  StoreID BIGINT NOT NULL,
  CreatedBy BIGINT NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  ModifiedDate TIMESTAMP DEFAULT NULL,
  UNIQUE (InvoiceNo)
);
ALTER TABLE Invoice ADD FOREIGN KEY (StoreID) REFERENCES Store (StoreID) ON DELETE RESTRICT ;
ALTER TABLE Invoice ADD FOREIGN KEY (CreatedBy) REFERENCES Users (UserID) ON DELETE RESTRICT;

CREATE TABLE InvoiceDetail (
  InvoiceDetailID BIGSERIAL PRIMARY KEY,
  InvoiceID BIGINT,
  ProductID BIGINT NOT NULL,
  Quantity INTEGER NOT NULL,
  Discount DECIMAL(9,5),
  Amount DECIMAL(12,5)
);
ALTER TABLE InvoiceDetail ADD FOREIGN KEY (InvoiceID) REFERENCES Invoice (InvoiceID) ON DELETE CASCADE ;
ALTER TABLE InvoiceDetail ADD FOREIGN KEY (ProductID) REFERENCES Product (ProductID) ON DELETE RESTRICT;

